# Generated by Django 5.0.6 on 2024-11-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('candidate', models.CharField(max_length=100)),
                ('party', models.CharField(max_length=100)),
                ('votes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TweetSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet', models.TextField()),
                ('sentiment', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
